plugins:
  - jekyll-seo-tag

# Name of your blog (this will show up at the top of your page and in the RSS feed)
title: opsmatters

# Short description (goes below the title; it will also be used in the RSS feed)
description: Open-source operational monitoring tools

# Your name, as you want it to appear underneath each post and in the footer
author: opsdemon

# URL pf the owner on github
author_url: https://github.com/opsdemon

# Your email if you want it to be linked on the contact page
author_email: gerald@opsmatters.com

# Email for questions and feedback
enquiries_email: enquiries@opsmatters.com

# URL pf the page on Facebook
facebook_url: https://www.facebook.com/opsmatters.uk
facebook_url_short: facebook.com/opsmatters.uk

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://opsmatters.com/
theme: jekyll-theme-leap-day
